<?php

declare(strict_types=1);

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method not allowed.']);
    exit;
}

function postStr(string $key, string $default = ''): string
{
    $v = $_POST[$key] ?? null;
    return is_string($v) ? $v : $default;
}

function jsonResponse(bool $success, string $message): never
{
    echo json_encode(['success' => $success, 'message' => $message]);
    exit;
}

$csrfPost   = $_POST['csrf_token']          ?? '';
$csrfHeader = $_SERVER['HTTP_X_CSRF_TOKEN'] ?? '';
$csrfCookie = $_COOKIE['csrf_token']        ?? '';

$csrfToken = $csrfHeader !== '' ? $csrfHeader : $csrfPost;

if ($csrfToken === '') {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'CSRF token invalid.']);
    exit;
}

if ($csrfCookie !== '' && $csrfToken !== $csrfCookie) {
    http_response_code(403);
    echo json_encode(['success' => false, 'message' => 'CSRF token invalid.']);
    exit;
}

const LOG_FILE    = '/tmp/updater.log';
const SCRIPT_FILE = '/tmp/updater-install.sh';

const ALLOWED_HOST_SUFFIX = '.unraid.net';

$action = postStr('action');

switch ($action) {
    case 'start_update':
        $url = postStr('url');

        if ( ! preg_match('#^https://#i', $url)) {
            jsonResponse(false, "URL must use HTTPS.");
        }
        $host = parse_url($url, PHP_URL_HOST);
        if ( ! is_string($host) || $host === '') {
            jsonResponse(false, "Invalid URL.");
        }
        if ( ! str_ends_with($host, ALLOWED_HOST_SUFFIX)) {
            jsonResponse(false, "URL host '{$host}' is not an authorized Unraid download server (must end in .unraid.net).");
        }

        $md5Raw = postStr('md5');
        $md5    = strtolower(preg_replace('/[^0-9a-fA-F]/', '', $md5Raw) ?? '');
        if ($md5Raw !== '' && strlen($md5) !== 32) {
            jsonResponse(false, "MD5 checksum must be exactly 32 hex characters.");
        }

        $installScript = <<<'BASH'
            #!/bin/bash
            # Unraid OS manual install script — generated by updater plugin

            URL="$1"
            MD5="$2"
            WORKDIR="/tmp/updater"

            set -o pipefail
            mkdir -p "$WORKDIR"

            echo "=== Unraid OS Update ==="
            date
            echo "Target: $URL"
            echo ""

            # Step 1: Download
            echo "[1/5] Downloading OS package"
            rm -f "$WORKDIR/unraid.zip"
            wget -O "$WORKDIR/unraid.zip" "$URL"
            DL_RC=$?
            echo ""
            if [[ $DL_RC -ne 0 ]] || [[ ! -s "$WORKDIR/unraid.zip" ]]; then
                echo "ERROR: Download failed (exit code $DL_RC) or file is empty."
                echo "FAILED"
                exit 1
            fi
            echo "Download complete."
            echo ""

            # Step 2: Verify checksum
            if [[ -n "$MD5" ]]; then
                echo "[2/5] Verifying MD5 checksum"
                ACTUAL=$(md5sum "$WORKDIR/unraid.zip" | awk '{print $1}')
                if [[ "${ACTUAL,,}" != "${MD5,,}" ]]; then
                    echo "ERROR: Checksum mismatch!"
                    echo "  Expected: $MD5"
                    echo "  Actual:   $ACTUAL"
                    echo "FAILED"
                    exit 1
                fi
                echo "Checksum verified."
            else
                echo "[2/5] No checksum provided — skipping verification."
            fi
            echo ""

            # Step 3: Extract
            echo "[3/5] Extracting package"
            rm -rf "$WORKDIR/unraid_install"
            unzip -o -d "$WORKDIR/unraid_install" "$WORKDIR/unraid.zip"
            UNZIP_RC=$?
            if [[ $UNZIP_RC -ne 0 ]] || [[ ! -s "$WORKDIR/unraid_install/bzroot" ]]; then
                echo "ERROR: Extraction failed (exit code $UNZIP_RC) or bzroot not found."
                echo "FAILED"
                exit 1
            fi
            echo "Extraction complete."
            echo ""

            # Step 4: Back up existing boot files
            echo "[4/5] Backing up current boot files to /boot/previous"
            [[ ! -d /boot/previous ]] && mkdir -p /boot/previous
            for f in /boot/bz*; do
                if [[ -f "$f" ]]; then
                    mv -f "$f" /boot/previous/
                    echo "  -> previous/$(basename "$f")"
                fi
            done
            if [[ -f /boot/changes.txt ]]; then
                mv -f /boot/changes.txt /boot/previous/
                echo "  -> previous/changes.txt"
            fi
            echo ""

            # Step 5: Install new boot files
            echo "[5/5] Installing new boot files to /boot"
            for f in "$WORKDIR/unraid_install/bz"*; do
                if [[ -f "$f" ]]; then
                    cp -f "$f" /boot/
                    echo "  + $(basename "$f")"
                fi
            done
            if [[ -f "$WORKDIR/unraid_install/changes.txt" ]]; then
                cp -f "$WORKDIR/unraid_install/changes.txt" /boot/
            fi
            echo ""

            echo "Syncing boot device..."
            sync -f /boot
            echo ""

            echo "--- Update Complete ---"
            echo "Reboot the system to apply the new Unraid OS version."
            echo ""
            echo "DONE"
            BASH;

        file_put_contents(SCRIPT_FILE, $installScript);
        chmod(SCRIPT_FILE, 0700);
        file_put_contents(LOG_FILE, '');

        $scriptEsc = escapeshellarg(SCRIPT_FILE);
        $urlEsc    = escapeshellarg($url);
        $md5Esc    = escapeshellarg($md5);
        $logEsc    = escapeshellarg(LOG_FILE);

        exec("nohup bash {$scriptEsc} {$urlEsc} {$md5Esc} > {$logEsc} 2>&1 & echo $!", $pidOut);
        $pid = (int)($pidOut[0] ?? 0);

        if ($pid === 0) {
            jsonResponse(false, "Failed to start update process.");
        }

        jsonResponse(true, "Update started (PID: {$pid}).");

        // no break
    case 'poll_log':
        $offset = max(0, (int)postStr('offset'));
        if ( ! file_exists(LOG_FILE)) {
            echo json_encode(['success' => true, 'content' => '', 'offset' => 0, 'done' => false, 'failed' => false]);
            exit;
        }
        $full = file_get_contents(LOG_FILE) ?: '';
        echo json_encode([
            'success' => true,
            'content' => substr($full, $offset),
            'offset'  => strlen($full),
            'done'    => str_contains($full, "\nDONE"),
            'failed'  => str_contains($full, "\nFAILED"),
        ]);
        exit;

    default:
        jsonResponse(false, "Unknown action.");
}
